title: Wu-Tang Clan
author: DJWithNoName
email: abc123@aol.com
description: > # this means to ignore newlines until "baseurl:"
  Puffy is good but Wu-Tang is the greatest

#theme
theme: minima

# social links
twitter_username: N/A # DO NOT include the @ character, or else the build will fail!
github_username:  N/A # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
